### ISSUE TITLE
Primalist Cloth tokens missing from the "Primalist Gear Tokens" list

### ISSUE THREAD

**Issue by PeteAndersen** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#14]
**Describe the bug**
Primalist Cloth tokens appear separate from other gear tokens when the `Merge primalist gear tokens` option is active. They are grouped into an Armor category by themselves, separate from other armor. 

**To Reproduce**
Set option to merge primalist gear tokens and have both cloth and non-cloth tokens in your bag or bank.

**Expected behavior**
All primalist gear tokens are grouped together. 

**Full Error Message**
No related error message. Dug through addon LUA and it looks like `PrimalistCloth` category is missing around line 2220 where the category merge is handled. 

![image](https://user-images.githubusercontent.com/11867035/231474404-9eeaa5d1-2f55-49c4-9905-55fc0db818d1.png)

**Comment by Zottelchen** [comment]
Hey, thanks for reporting! Looks like I messed something up upstream😅 I will fix this later today.

**Comment by Zottelchen** [comment]
Thanks again! Just pushed version 2.2.6 which is currently building. This should fix the issue :)

**Comment by PeteAndersen** [comment]
Thank you for all your hard work! Couldn't play without this addon.
