### ISSUE TITLE
Items in wrong category

### ISSUE THREAD

**Issue by KatyPurry** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#17]
### Category Name

Miscellaneous

### Item IDs / Item Names

```Shell
205982
204802
```

Maybe in Cavern Currencies ? Or a new category ?

**Comment by Zottelchen** [comment]
Hi, once again thank you for reporting :)

I've added the dig maps to Cavern Currencies and the Teleport Scroll to Zskera Vault. They should be included with the 3.2.3 version, which is building right now 👍

**Comment by KatyPurry** [comment]
Thank you !
