### ISSUE TITLE
Errors upon login

### ISSUE THREAD

**Issue by Tednik** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#2]
2x Interface\FrameXML\Bindings.xml:1 AdiBags_Dragonflight/AdiBags_Dragonflight.lua:1 AdiBags_Dragonflight/AdiBags_Dragonflight.lua:803: '}' expected (to close '{' at line 801) near 'Alchemy'

2x AdiBags_Dragonflight/AdiBags_Dragonflight.lua:1 AdiBags_Dragonflight/AdiBags_Dragonflight.lua:803: '}' expected (to close '{' at line 801) near 'Alchemy'

turn addon on and log in to game
**Expected behavior**

wont load in adibags to choose options

**Comment by Zottelchen** [comment]
Hey, sorry about that!😅 This should be fixed in the upcoming version 1.1.5.
