### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by Pegoth** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#27]
### Category Name

Runes

### URLs

https://www.wowhead.com/item=204971/hissing-rune
https://www.wowhead.com/item=204972/hissing-rune
https://www.wowhead.com/item=204973/hissing-rune

**Comment by Zottelchen** [comment]
Hi, thanks for reporting this :)

I've included it in the upcoming version 👍
