### ISSUE TITLE
AdiBags being deprecated -- please read.

### ISSUE THREAD

**Issue by Cidan** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#31]
Hi there,

I'm the maintainer of AdiBags, and we have made a decision to halt all development on AdiBags and move over to a new codebase and addon called BetterBags. The new addon is written and maintained by the same team, but is significantly faster and easier to read/use. We're rounding out some of the key features of BetterBags now, including item filtering. The addon is available in alpha to download today, and we'll be moving onto a full beta in the coming days.

I would love to figure out how we can incorporate either your changes directly, or at least accommodate a plugins system to support your work. Feel free to reach out on the BetterBags discord!

github.com/Cidan/BetterBags

Thanks!

**Comment by Zottelchen** [comment]
Joined the discord.👍

**Comment by JourneyOver** [comment]
@Zottelchen are there any plans on making an update to betterbags for both this and https://github.com/Zottelchen/adibags-creator-action ?

**Comment by Zottelchen** [comment]
@JourneyOver Yes, but it will take some time. I can't make any promises but will take a look this week.

**Comment by Zottelchen** [comment]
@JourneyOver So, currently it does not look worth the effort to port the creator/addons. Not saying it won't happen, but not anytime soon. While BetterBags itself is easier to use, it makes it harder for more extensive addons to expand upon it, at least for now:

- Categories are now saved by the main addon - which is great for custom lists, but less so for addon lists, as users can add/remove IDs at their will. Lets say a user want to remove an item from the category - it will be readded upon the next load of the addon unless you write additional code to handle that / only load once per version so you can update, etc. So now it seems we moved from maintaining simple databases to writing migration code. Similar, if the user adds an item and you use the API to clear the category ([e.g. the example plugin says to put categories in a "known state"](https://github.com/Cidan/BetterBags/blob/main/examples/plugin/plugin.lua#L28-L32)) it will be removed unless once again the migration logic. 
- There is no possibility currently to toggle only some categories. Also no possibility to add just some custom configuration - everything has to be done from scratch. I assume that will come at some point. This is especially annoying for split categories like elemental items. 
- The dev already said, that he will implement some additional features, like changing the colors of the categories. Also there was an import/export system announced (similiar to WeakAura) - which does not have the "migration" issue above. So maybe plugins simply aren't needed anymore at some point. But currently that is very unclear, Betterbags is still in very early development. 

So, yeah, not very optimistic for my addons and this creator as of now. Additionally I am currently not actively playing, so the incentive to fix this is nearly non-existant, sorry😅

**Comment by Cidan** [comment]
I'm happy to work with you @Zottelchen and look at some of this, however, if you're actively not playing anymore, I definitely don't want to pull you into this. I think for some of the stuff you've mentioned, there is a correct way of doing what you need, but that's okay too!

Longer term, I do think you're right -- once import and export have been added, the need for static lists will hopefully subside and people can just paste snippets.

Thanks again for all your effort!

**Comment by Zottelchen** [comment]
@Cidan No worries :) I am looking forward to what you can do with BetterBags :) Maybe I will create a central BetterBags snippet sharing website instead ;)

**Comment by JourneyOver** [comment]
> @JourneyOver So, currently it does not look worth the effort to port the creator/addons. Not saying it won't happen, but not anytime soon. While BetterBags itself is easier to use, it makes it harder for more extensive addons to expand upon it, at least for now:
> 
> * Categories are now saved by the main addon - which is great for custom lists, but less so for addon lists, as users can add/remove IDs at their will. Lets say a user want to remove an item from the category - it will be readded upon the next load of the addon unless you write additional code to handle that / only load once per version so you can update, etc. So now it seems we moved from maintaining simple databases to writing migration code. Similar, if the user adds an item and you use the API to clear the category ([e.g. the example plugin says to put categories in a "known state"](https://github.com/Cidan/BetterBags/blob/main/examples/plugin/plugin.lua?rgh-link-date=2024-02-02T23%3A50%3A44Z#L28-L32)) it will be removed unless once again the migration logic.
> * There is no possibility currently to toggle only some categories. Also no possibility to add just some custom configuration - everything has to be done from scratch. I assume that will come at some point. This is especially annoying for split categories like elemental items.
> * The dev already said, that he will implement some additional features, like changing the colors of the categories. Also there was an import/export system announced (similiar to WeakAura) - which does not have the "migration" issue above. So maybe plugins simply aren't needed anymore at some point. But currently that is very unclear, Betterbags is still in very early development.
> 
> Additionally I am currently not actively playing, so the incentive to fix this is nearly non-existant, sorry


Def understandable on all accounts, I'm still stuck using adibags anyways atm since I have so many random things that aren't setup for betterbags so it's not a issue or anything if you don't want to tackle messing with betterbags any for the time being :P also currently not actively playing much either since my guild has decided to not raid anymore for the season sadly and I'm getting kind of burnt out from pushing really hard the first couple weeks of season 3.
