### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by Vilaric** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#32]
### Category Name

Potions

### URLs

https://www.wowhead.com/item=207041/potion-of-withering-dreams
https://www.wowhead.com/item=207040/potion-of-withering-dreams
https://www.wowhead.com/item=207039/potion-of-withering-dreams

### Item IDs

```Shell
207041
207040
207039
```

**Comment by Zottelchen** [comment]
Hi, thanks for reporting this :)

I've included it in the upcoming version 👍
