### ISSUE TITLE
Missing 10.2 Dream Sparks

### ISSUE THREAD

**Issue by naeshy** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#34]
### Category Name

Dreaming Crests

### URLs

https://www.wowhead.com/item=206959/spark-of-dreams
https://www.wowhead.com/item=208396/splintered-spark-of-dreams

### Item IDs

```Shell
206959
208396
```

**Comment by Zottelchen** [comment]
Hi, thanks for reporting this :)

I've included it in the upcoming version, but in the different category "Item Level Upgrades", as previous sparks where in that one as well 👍

**Comment by naeshy** [comment]
Awesome, thanks!
