### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Milky063** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#36]
**Describe the bug**
Its a lua error

**To Reproduce**
1. Go to '...' i was tanking on my warrior and have no idea what happen. was pushing buttons when i'm attacking. 

**Expected behavior**
I expected it to work. 

**Full Error Message**
```
Put the error message in here!
```
2x [ADDON_ACTION_BLOCKED] AddOn 'AdiBags' tried to call the protected function 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:189: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:228: in function `AddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:142: in function `CheckAddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:153: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:102: in function `OnEvent'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:99: in function `SignalEvent'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:106: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:105>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:109: in function `OnEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:111: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:110>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Zottelchen** [comment]
Hey, thanks for reaching out. From the logs it seems that this isn't an issue with this add-on, which only provides filters, but with the main addon AdiBags (https://github.com/AdiAddons/AdiBags). You may have more luck filing a bug report there. :) Please be aware that AdiBags seems to be phased out soon in favor of BetterBags, so a bug fix may not immediately happen.
