### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by KatyPurry** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#5]
**Is your feature request related to a problem? Please describe.**
I'm playing in French, it will be cool to have category items in french !

**Describe the solution you'd like**
Add internationalization in lua files

**Describe alternatives you've considered**

**Additional context**

**Comment by Zottelchen** [comment]
Thank you for this suggestion. This in the works, but requires some more time than just adding a few IDs :)

**Comment by KatyPurry** [comment]
Awesome ! Thank you for your hard work !

**Comment by Zottelchen** [comment]
@Zazou49 Thank you for your patience😊 Localization is now available and everyone can contribute on Curseforge :)

**Comment by KatyPurry** [comment]
> @Zazou49 Thank you for your patience😊 Localization is now available and everyone can contribute on Curseforge :)

Awesome ! Thank you, I’ll add French loc asap.
