### ISSUE TITLE
New Category: Renown Tokens

### ISSUE THREAD

**Issue by KatyPurry** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#6]
### Category Name

Renown Tokens

### In-Game Color

#1eff00

### In-Game Description

Renown Tokens of major factions

### README.md Description

Renown Tokens of major factions

### Item IDs

```Shell
192055
200093
200071
199906
```

**Comment by Zottelchen** [comment]
Thank you so much for sharing this list! It is implemented and will appear in the version 1.1.8 soon! :)
