### ISSUE TITLE
New Category: Wrathion and Sabellian Reputation

### ISSUE THREAD

**Issue by KatyPurry** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#7]
### Category Name

Wrathion and Sabellian Reputation

### In-Game Color

#c1ab86

### In-Game Description

Wrathion and Sabellian Reputation items

### README.md Description

Wrathion and Sabellian Reputation items

### Item IDs

```Shell
191251
193201
191264
201991
200224
```

**Comment by Zottelchen** [comment]
Thank you so much for sharing this list! It is implemented and will appear in the version 1.1.8 soon! :)
