### ISSUE TITLE
Missing IDs for skinning profession knowledge

### ISSUE THREAD

**Issue by rainkius** [Zottelchens-WoW-Addons/AdiBags-Dragonflight#9]
### Category Name

Profession Knowledge

### Item IDs

```Shell
201023
202016
198841
200982
201278
199128
201289
194040
198527
```

**Comment by rainkius** [comment]
For some reason, Wowhead doesn't include skinning in the "requires a profession" filter, so these all got left out of the last list I submitted - did not duplicate Curious Hide Scraps bc I know someone else submitted that already :)

**Comment by Zottelchen** [comment]
Thank you for reporting! I've added these IDs and they will be part of the upcoming version 1.1.10 :)
